CREATE TABLE patient (patient_id INT PRIMARY KEY, nom VARCHAR(100), prenom VARCHAR(100), naissance DATE);

-- Insertion des papatients
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (1, 'Altrain', 'Lucie', 2001-07-12);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (2, 'Retarier', 'Luc', 2005-02-17);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (3, 'Fléchier', 'Laëtitia', 1983-11-05);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (4, 'Crevier', 'Mathieu', 1971-10-01);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (5, 'Riqueti', 'Frédéric', 1991-07-16);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (6, 'Jauffret', 'Jordan', 1995-07-24);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (7, 'Bullion', 'Timothée', 1997-07-29);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (8, 'Compere', 'Bruno', 1991-07-13);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (9, 'Pichard', 'Barthélemy', 1984-07-04);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (10, 'Thibodeau', 'Kevin', 1995-07-04);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (11, 'Robineau', 'Joël', 1998-07-08);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (12, 'Lecerf', 'Daniel', 1998-07-06);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (13, 'Barthet', 'Axel', 1991-07-16);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (14, 'Calvet', 'Albertine', 2001-07-11);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (15, 'Bullion', 'Marie-Noëlle', 1992-07-26);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (16, 'Le Sueur', 'Mélodie', 2002-07-22);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (17, 'Pichard', 'Julia', 2005-07-21);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (18, 'Soyer', 'Carine', 2009-07-23);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (19, 'Pierrat', 'Blanche', 1976-07-25);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (20, 'Celice', 'Catherine', 1984-07-20);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (21, 'Houdin', 'Carole', 2001-07-15);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (22, 'Carbonneau', 'Alphonsine', 1972-07-06);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (23, 'Seyrès', 'Frédérique', 1978-07-01);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (24, 'Toussaint', 'Néo', 1967-07-03);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (25, 'Bombelles', 'Maël', 1975-07-14);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (26, 'Lortie', 'Christopher', 1998-07-23);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (27, 'Pichard', 'Jean-Charles', 1967-07-29);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (28, 'Morel', 'Sylviane', 1968-07-27);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (29, 'Chuquet', 'Godeleine', 2003-07-27);
INSERT INTO patient (patient_id, nom, prenom, naissance) VALUES (30, 'Azéma', 'Gervaise', 1975-07-19);
